services:
  - type: web
    name: diabetes-prediction-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn index:app
    env: python
    python:
      version: 3.12.4